### ISSUE TITLE
Non 3D secure transactions are not allowed

### ISSUE THREAD

**Issue by MavericMujeeb** [Tap-Payments/goSellSDK-AndroidX#12]
Hi,

I am getting below error
{ "errors": [{ "code": "1109", "description": "Non 3D secure transactions are not allowed"}]}

**Comment by AhlaamK-tap** [comment]
Hi, @ MavericMujeeb could  you please send an email to a.kazi@tap.company with all the details , logs , keys and sdk version. thanks.
