### ISSUE TITLE
Issue in running sample SDK 

### ISSUE THREAD

**Issue by varunjain0888** [Tap-Payments/goSellSDK-AndroidX#13]
Could not determine the dependencies of task ':goSellSDKSample:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':goSellSDKSample:debugCompileClasspath'.
   > Could not resolve com.github.Tap-Payments:TapColorsKit-Android:1.0.
     Required by:
         project :goSellSDKSample
      > Could not resolve com.github.Tap-Payments:TapColorsKit-Android:1.0.
         > Could not get resource 'https://jitpack.io/com/github/Tap-Payments/TapColorsKit-Android/1.0/TapColorsKit-Android-1.0.pom'.
            > Could not GET 'https://jitpack.io/com/github/Tap-Payments/TapColorsKit-Android/1.0/TapColorsKit-Android-1.0.pom'. Received status code 403 from server: Forbidden

**Comment by kanbi298** [comment]
Did you find any solutions related to this issue?

**Comment by AhlaamK-tap** [comment]
Hi, @varunjain0888  Could you please share the details with sdk version used to a.kazi@tap.company
