### ISSUE TITLE
Could not find method implementation() for arguments [com.github.Tap-Payments:goSellSDK-AndroidX:3.11.2] 

### ISSUE THREAD

**Issue by m-tbox** [Tap-Payments/goSellSDK-AndroidX#16]
Hi,

I am using jitpack in the installation step but I am getting this error.

`Could not find method implementation() for arguments [com.github.Tap-Payments:goSellSDK-AndroidX:3.11.2] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler`

**Comment by AhlaamK-tap** [comment]
Hi, @m-tbox  Could you please share the error details to a.kazi@tap.company
