### ISSUE TITLE
Cant pass reference id

### ISSUE THREAD

**Issue by nvpnair** [Tap-Payments/goSellSDK-AndroidX#19]
var reference:Reference?=null  
reference= Reference(FirebaseAuth.getInstance().currentUser.displayName,"TAP", priceamount.toString(),trackid,tranid,refid)
 sdkSession.setPaymentReference(reference)

I can't pass the reference id after payment... please let me know... if there is anything wrong. in passing parameter

**Comment by AhlaamK-tap** [comment]
#5 With reference to this
