### ISSUE TITLE
do you have sdk for react native ?

### ISSUE THREAD

**Issue by LzazSports** [Tap-Payments/goSellSDK-AndroidX#2]
I want to use tap.company sdk, looking for react native solution

**Comment by HaithamSheshtawy** [comment]
not for now.

**Comment by mushtaque87** [comment]
Yes now they have ..

**Comment by HaithamSheshtawy** [comment]
Hi, currently react native SDK is available
https://www.npmjs.com/package/@tap-payments/gosell-sdk-react-native
