### ISSUE TITLE
Price is coming 0 when I add PaymentItems

### ISSUE THREAD

**Issue by shafeekghaseel** [Tap-Payments/goSellSDK-AndroidX#21]
sdkSession?.setPaymentItems(payTabPaymentItems())

private fun payTabPaymentItems(): ArrayList<PaymentItem>? {
        val items = ArrayList<PaymentItem>()
        var paymentItemBuilder =
            company.tap.gosellapi.open.models.PaymentItem.PaymentItemBuilder(
                "Recharge",
                Quantity(MeasurementUnit { Measurement.UNITS }, BigDecimal(1)),
                BigDecimal(5)
            )
        items.add(paymentItemBuilder.build())
        return items
    }

Its working If we don't add payment items
![msg184796338-111267](https://user-images.githubusercontent.com/52627420/141101389-5a8669bd-bfc6-4743-aa73-a519571aa020.jpg)
.

**Comment by AhlaamK-tap** [comment]
@shafeekghaseel 
Please ensure you are sending the amount well , kindly check the below
 ```
items.add(
                PaymentItemBuilder("", Quantity(KILOGRAMS, BigDecimal.ONE), BigDecimal.ONE)
                        .description("Description for test item #1")
                        .discount(AmountModificator(FIXED, BigDecimal.ZERO))
                        .taxes(null)
                        .build())
```
Thanks
