### ISSUE TITLE
Requires JCenter which is now deprecated.

### ISSUE THREAD

**Issue by BilalZurmati** [Tap-Payments/goSellSDK-AndroidX#29]
Currently the SDK has a dependency

`implementation 'jp.wasabeef:blurry:2.1.1'`

which is available in jCenter(), as of now JCenter is deprecated and this SDK requires to add jCenter into gradle to get rid of the error.

could you please upgrade it to latest version like below

`implementation 'jp.wasabeef:blurry:4.0.1'`

or is it possible to contribute because I have seen too many flaws and redundancy in code.

**Comment by AhlaamK-tap** [comment]
Please update to latest version
```
dependencies {
	        implementation 'com.github.Tap-Payments:goSellSDK-AndroidX:3.17.2'
	}
```
Thanks
