### ISSUE TITLE
Could not find com.github.Tap-Payments:goSellSDK-AndroidX:3.2.3

### ISSUE THREAD

**Issue by peymancyb** [Tap-Payments/goSellSDK-AndroidX#3]
Hi
i am trying to get the sdk but getting this error, and before this version the sdk was not downloading at all, and the error was 
 > Could not GET 'https://jitpack.io/com/github/Tap-Payments/TapCardValidator-Android/1.0.7/TapCardValidator-Android-1.0.7.pom'. Received status code 401 from server: Unauthorized

**Comment by HaithamSheshtawy** [comment]
Can you integrate with latest:
implementation 'com.github.Tap-Payments:goSellSDK-AndroidX:3.2.4'

**Comment by peymancyb** [comment]
Yes! thanks the last one worked.
