### ISSUE TITLE
SDK uses default 'app_name' string resource

### ISSUE THREAD

**Issue by frankovlahov** [Tap-Payments/goSellSDK-AndroidX#30]
The issue: 
The GoSellSDK uses the default 'app_name' string resource for ar, de and tr languages which causes problems if our application doesn't support those languages leading to the application name being 'GoSellApi' if the user's phone is set to any of these languages.

Potential fix:
Either remove or rename this 'app_name' string resource from the strings.xml (for each language)

**Comment by AhlaamK-tap** [comment]
Hi @frankovlahov It's fixed with the latest version you may try out ` implementation 'com.github.Tap-Payments:goSellSDK-AndroidX:3.18.10'`
