### ISSUE TITLE
This library depends on an non-androidx library (material-dialogs) 

### ISSUE THREAD

**Issue by mirland** [Tap-Payments/goSellSDK-AndroidX#34]
This [library](https://github.com/Tap-Payments/goSellSDK-AndroidX/blob/master/library/build.gradle#L68C5-L70C6) is using `com.afollestad.material-dialogs:core:0.9.6.0` which does not use android x.

That library should be updated, so we can remove jetifier.

**Comment by AhlaamK-tap** [comment]
@mirland 
Please use the latest version 
	```
dependencies {
	        implementation 'com.github.Tap-Payments:goSellSDK-AndroidX:3.19.20'
	}

```
We no longer are using it now
Thanks
