### ISSUE TITLE
Could not determine artifacts for com.github.Tap-Payments:TapCardValidator-Android:2.1.0

### ISSUE THREAD

**Issue by peymancyb** [Tap-Payments/goSellSDK-AndroidX#4]
Hi,
this error happens on version 3.2.5
```Could not determine the dependencies of task ':app:lintVitalDemoRelease'.
> Could not resolve all dependencies for configuration ':app:demoReleaseRuntimeClasspath'.
   > Could not determine artifacts for com.github.Tap-Payments:TapCardValidator-Android:2.1.0
      > Could not get resource 'https://jitpack.io/com/github/Tap-Payments/TapCardValidator-Android/2.1.0/TapCardValidator-Android-2.1.0.aar'.
         > Could not HEAD 'https://jitpack.io/com/github/Tap-Payments/TapCardValidator-Android/2.1.0/TapCardValidator-Android-2.1.0.aar'. Received status code 401 from server: Unauthorized
```

**Comment by HaithamSheshtawy** [comment]
I integrated it with empty project and it works fine, so could u please tell me
what version you are using for build gradle? is it com.android.tools.build:gradle:3.5.0?

**Comment by peymancyb** [comment]
@HaithamSheshtawy thanks for the response, yes it is `com.android.tools.build:gradle:3.5.0`

**Comment by HaithamSheshtawy** [comment]
can you share log with me and also your gradle
h.sheshtawy@tap.company

**Comment by peymancyb** [comment]
Thank you @HaithamSheshtawy, I have already shared it to the mentioned email address.

**Comment by matir91** [comment]
I'm facing exactly the same issue in the `goSellSDK-Android` library (version `2.4.6`).

**Comment by HaithamSheshtawy** [comment]
now it's public could u please test

**Comment by HaithamSheshtawy** [comment]
Our jitPack artifact report for the latest release:
<img width="1906" alt="image" src="https://user-images.githubusercontent.com/45915302/68330269-01258100-00e4-11ea-973e-5e0819681fa2.png">

**Comment by peymancyb** [comment]
@HaithamSheshtawy Thanks for the update, yes now it's fixed!

**Comment by HaithamSheshtawy** [comment]
Great

**Comment by HaithamSheshtawy** [comment]
> @HaithamSheshtawy Thanks for the update, yes now it's fixed!

can u please close the issue if it's fixed

**Comment by peymancyb** [comment]
Yes sure! thanks.
