### ISSUE TITLE
[3.2.0] Order reference id is not sent in some cases

### ISSUE THREAD

**Issue by mirland** [Tap-Payments/goSellSDK-AndroidX#5]
Hi, we received an email saying that:
"We have checked the logs, for all android SDK transactions, we are not receiving the order reference number from your end".

And then they attached 7 transaction ids.

My method that initializes the `SDKSession` receive the order id, as not nullable param (`orderId`) and it performs some operations. One of the most importan ones are:
```kotlin
  SDKSession()
      .apply {
        .....
        setPaymentReference(Reference(null, null, null, null, null, orderId))
        setPaymentDescription(DISPLAY_NAME.format(orderId))
}
```
`DISPLAY_NAME` name is a constant defined by my project name concated by the order id: 
`private const val DISPLAY_NAME = "Company Order %s"`

I checked all transactions that you sent me (using your API) and in all cases the payment description contains the `orderId`. `orderId` is an inmutable param, so that means that I'm sending the payment reference id in all these cases.
  
Thanks!

**Comment by AhlaamK-tap** [comment]
HI, Can you pass it through SDKSession object as bellow:
        // Payment Reference
        `sdkSession.setPaymentReference(new Reference("acquirer", "gateway", "payment", "track", "transaction","order")); `
regards,

**Comment by matir91** [comment]
But it's what I'm doing, check my line. You are writing Java code and I'm writing kotlin code but it's basically the same. What should I change? Also it doesn't make sense, because most of my transactions contains the order reference id. However, some of them they don't have it. Furthermore, what it's more strange is that in all cases the description contains the order id, so can you check it please?

**Comment by AhlaamK-tap** [comment]
Dear,
        What I meant is when you initiated SDK Session and pass reference object that contains order id , the SDK will wrap it inside Charge object and forward it to the backend, hence the backend will return it back to SDK embedded inside Charge response, then SDK will notify your app with the charge response that contains order id inside charge response through the delegate function.

So, If you received order id in one transaction then it has to be always exist with all transactions.

could u please provide me with the following details:
  - SDK version integrated with your App.
  - Log if you can that matches your case. "please include printing charge response object details from your side"

you can send email to h.sheshtawy@gmail.com
regards,

**Comment by nvpnair** [comment]
@mirland have you solved this issue?

**Comment by mirland** [comment]
The reference id is needed to validate that an order is paid only once
We added a hack, before invoking tap sdk, we call an endpoint in our backend to authorize the payment. So if the reference id is not present, we use the order id from the description, so the backend can validate if the order is already paid or not. 
However, I believe that this issue is not happening anymore, I mean, I'm not sure but I didn't see an alert talking about that
